### PR TITLE
Everything working

### PR DESCRIPTION
**Pull request by 117649**

### CODE REVIEW

**Comment by 117649** [comment]
You are too late everything is working now.

**Comment by p1usminus** [comment]
Sorry, I'm still here!

Okay, I am trying out 1.6.5.1 now - this is _amazing_! How does the colour selection work? When I first tried to update Roomy I did not understand it at all (and honestly I still don't, lol)

Does it keep a list of each bookmark-item in roomybookmarkstoolbar.sqlite and store the changed CSS there? I assume that is what the rbtid is for?

The colour db seems to reset without restarting the browser, so the alert [here](https://github.com/117649/roomybookmarksredux/blob/master/src/content/colorMenu.js#L149) is no longer required, but that's easy, I can fix that 😁

And the hidenofavicon fix... that has been bugging me for **so** long!

I will merge the PR and clean up some of the text a little later today, thank you

**Comment by 117649** [comment]
Firefox now use a new structure of guid and api for storage bookmarks. Just switched to use that and it is better since it give the guid of every bookmark item.  
RBT used to keep a table of id and colors value in 'roomybookmarkstoolbar.sqlite' didn't change any of that except the type of the id has to be change to string to match the new id value used. 
CSS is generated on the fly like before it select the 'rbtid' attribute which was the index of the item in tool bar but now the guid for that unique bookmark. 
Use a mutation observer to set the attribute on the items separated the process with CSS apply so no delay needed and only need to register CSS when there is actual change.  
Added a check to delete total empty and target less rows from 'roomybookmarkstoolbar.sqlite' while going through it. Tweaked it so it now accept any of 2 color setting be empty.
Like the changes on bookmarks now Firefox use a new kind of protocol to refer to a favicon cache and you have to fetch the data and do a comparison to know if it is the default favicon and be able to mark it by attribute. This process is kind of slow(not yet to make human annoyed) you may want to implement switches to turn it off when it not needed. Be sure to test it thoroughly if you do.
Methods relate to fetch bookmark and favicon data have been made async to match the api they used.

**Comment by 117649** [comment]
Found that incomplete or empty css has been registered, fixed that(I hope) and improved performance.

**Comment by 117649** [comment]
I moved farther by removing usage of Overlays.jsm and ChromeManifest.jsm.
They are not very necessary since we really have a little more then zero elements to overlay on the browser chrome.
See if you like that.
https://github.com/117649/roomybookmarksredux/commit/910ff87197fa05d1bcda0c5e5b5f92c992bdff52

**Comment by p1usminus** [comment]
> 
> 
> I moved farther by removing usage of Overlays.jsm and ChromeManifest.jsm.
> They are not very necessary since we really have a little more then zero elements to overlay on the browser chrome.

You are quite right! I will try it shortly 😀

**Pull request merged**
