### PR TITLE
Direct open option dialog and remove warning msg from addon mgr

### PR DESCRIPTION
**Pull request by 117649**
No flashing blank page thus no unintentional scroll of tab bar.

### CODE REVIEW

**Comment by p1usminus** [comment]
Wow sorry I just saw this

I will merge this soon, thank you

**Comment by 117649** [comment]
> 
> 
> Wow sorry I just saw this
> 
> I will merge this soon, thank you

Hold on!
I've just see this: https://github.com/xiaoxiaoflood/firefox-scripts/commit/5403e13336eff759162c115f37c50ecde32d3e25

Looks like the creator of bootstrap loader have update on this and restore option type 1. That means you can just set `<optionsType/>` to 1 in 'install.rdf' and it should open a dialog.

**Comment by 117649** [comment]
@p1usminus I've updated this pr switched to use newest bootstrap and use a pref: "extensions.roomybookmarkstoolbar.hide_warring" to decided if to hide the warring. User can manually set this to true in `about:config` if they don't want the warring sign.

**Comment by p1usminus** [comment]
oh, cool! I will update this weekend, promise :blush:

**Comment by p1usminus** [comment]
Done!

I think Waterfox (G3.2.1) is using an old version of BootstrapLoader and I cannot update manually, so the new addon version does not install because of the new optionsType
>WARN	Invalid XPI: Error: Install manifest specifies unknown optionsType: 1

Waterfox users will just have to wait :p

**Comment by 117649** [comment]
> 
> 
> Done!
> 
> I think Waterfox (G3.2.1) is using an old version of BootstrapLoader and I cannot update manually, so the new addon version does not install because of the new optionsType
> 
> > WARN	Invalid XPI: Error: Install manifest specifies unknown optionsType: 1
> 
> Waterfox users will just have to wait :p

This could be solved by adding some fall back logic.
 
If you decided worth doing it.

**Comment by p1usminus** [comment]
> 
> If you decided worth doing it.

I don't think so 😁 - Waterfox will block/ignore the update of the addon until BootstrapLoader.jsm within the browser is updated, and the previous version is working okay.

**Pull request merged**
